export const getRelativeDate = (daysOffset) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

export const getDaysDifference = (eventDateStr) => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const eventDate = new Date(eventDateStr + "T00:00:00");
  return Math.round((eventDate - today) / (1000 * 60 * 60 * 24));
};

export const CATEGORIES = ["Todos", "Palestras", "Workshops", "Eventos", "Seminários"];

// Faculdade multi-curso -- agora cobre várias áreas, não só TI.
export const COURSES = [
  "Todos",
  "Engenharia de Software",
  "Sistemas de Informação",
  "Engenharia Civil",
  "Engenharia Mecânica",
  "Arquitetura e Urbanismo",
  "Medicina",
  "Odontologia",
  "Direito",
  "Administração",
  "Psicologia",
  "Comunicação Social",
  "Pedagogia",
  "Geral",
];

export const MOCK_USER = {
  id: 42,
  name: "Mariana Silva",
  course: "Engenharia de Software",
  semester: "6º Período",
  matricula: "2023001",
  totalHoursNeeded: 120,
  hoursCompleted: 92,
  avatar: "https://i.pravatar.cc/150?img=5",
  notifications: 3,
  role: 'aluno'
};

export const MOCK_PROF = {
  id: 7,
  name: "Prof. Roberto Costa",
  department: "Coordenação Acadêmica",
  matricula: "PROF-0042",
  avatar: "https://i.pravatar.cc/150?img=11",
  role: 'professor'
};

// Lista auxiliar de alunos fictícios para popular listas de inscritos.
// Mistura de cursos para refletir o caráter multi-faculdade do sistema.
export const MOCK_STUDENTS = [
  { id: 42, name: "Mariana Silva",         matricula: "2023001", course: "Engenharia de Software",    avatar: "https://i.pravatar.cc/150?img=5"  },
  { id: 43, name: "Lucas Bergmann",        matricula: "2023002", course: "Sistemas de Informação",    avatar: "https://i.pravatar.cc/150?img=12" },
  { id: 44, name: "Ana Beatriz Ferreira",  matricula: "2023003", course: "Medicina",                  avatar: "https://i.pravatar.cc/150?img=47" },
  { id: 45, name: "João Pedro Oliveira",   matricula: "2023004", course: "Direito",                   avatar: "https://i.pravatar.cc/150?img=33" },
  { id: 46, name: "Carolina Mendes",       matricula: "2023005", course: "Arquitetura e Urbanismo",   avatar: "https://i.pravatar.cc/150?img=23" },
  { id: 47, name: "Rafael Souza",          matricula: "2023006", course: "Engenharia Civil",          avatar: "https://i.pravatar.cc/150?img=15" },
  { id: 48, name: "Isabela Rocha",         matricula: "2023007", course: "Psicologia",                avatar: "https://i.pravatar.cc/150?img=49" },
  { id: 49, name: "Gabriel Tavares",       matricula: "2023008", course: "Administração",             avatar: "https://i.pravatar.cc/150?img=68" },
  { id: 50, name: "Beatriz Almeida",       matricula: "2023009", course: "Medicina",                  avatar: "https://i.pravatar.cc/150?img=44" },
  { id: 51, name: "Pedro Henrique Lima",   matricula: "2023010", course: "Direito",                   avatar: "https://i.pravatar.cc/150?img=60" },
  { id: 52, name: "Larissa Carvalho",      matricula: "2023011", course: "Comunicação Social",        avatar: "https://i.pravatar.cc/150?img=26" },
  { id: 53, name: "Vinicius Moreira",      matricula: "2023012", course: "Engenharia Mecânica",       avatar: "https://i.pravatar.cc/150?img=51" },
  { id: 54, name: "Fernanda Antunes",      matricula: "2023013", course: "Odontologia",               avatar: "https://i.pravatar.cc/150?img=20" },
  { id: 55, name: "Thiago Resende",        matricula: "2023014", course: "Pedagogia",                 avatar: "https://i.pravatar.cc/150?img=70" },
];

export const INITIAL_EVENTS = [
  // ============== CONCLUÍDOS ==============
  {
    id: 1001,
    title: "Introdução ao Git e GitHub na prática",
    category: "Workshops",
    date: getRelativeDate(-21),
    time: "09:00 - 11:00",
    location: "Laboratório 1, Bloco C",
    hours: 2,
    spots: 40,
    enrolled: 38,
    speaker: "Profa. Helena Duarte",
    description: "Mão na massa em Git: branches, merges, pull requests e estratégias de versionamento usadas no mercado.",
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=800&q=80",
    isEnrolled: true,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
  },
  {
    id: 1002,
    title: "Mulheres que mudaram a Computação",
    category: "Palestras",
    date: getRelativeDate(-10),
    time: "19:00 - 20:30",
    location: "Auditório Principal, Bloco A",
    hours: 2,
    spots: 120,
    enrolled: 97,
    speaker: "Dra. Cláudia Mascarenhas",
    description: "De Ada Lovelace a Grace Hopper, uma jornada por trajetórias femininas que moldaram a tecnologia moderna.",
    image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=800&q=80",
    isEnrolled: true,
    courses: ["Engenharia de Software", "Sistemas de Informação", "Geral"],
  },
  {
    id: 1003,
    title: "Júri Simulado: O caso do contrato eletrônico",
    category: "Eventos",
    date: getRelativeDate(-7),
    time: "14:00 - 18:00",
    location: "Sala de Audiências, Bloco D",
    hours: 4,
    spots: 50,
    enrolled: 48,
    speaker: "Prof. Augusto Marinho",
    description: "Encenação completa de um júri envolvendo validade de contratos assinados digitalmente. Alunos atuam como acusação e defesa.",
    image: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Direito"],
  },
  {
    id: 1004,
    title: "Maratona de Algoritmos — Eliminatória",
    category: "Eventos",
    date: getRelativeDate(-3),
    time: "08:00 - 17:00",
    location: "Laboratório 5, Bloco C",
    hours: 8,
    spots: 60,
    enrolled: 58,
    speaker: "Comissão de Competições",
    description: "Etapa local da maratona universitária. Times de 3 alunos resolvendo problemas em 9 horas seguidas.",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
  },

  // ============== HOJE / AMANHÃ ==============
  {
    id: 1005,
    title: "Atualizações em Cardiologia 2026",
    category: "Palestras",
    date: getRelativeDate(0),
    time: "08:00 - 12:00",
    location: "Auditório do Hospital Universitário",
    hours: 4,
    spots: 180,
    enrolled: 171,
    speaker: "Dr. Eduardo Pimentel (Inc) / Dra. Helena Castro (HUFF)",
    description: "Painel multidisciplinar com as principais diretrizes atualizadas em cardiologia clínica, intervencionista e prevenção primária.",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Medicina"],
  },
  {
    id: 1006,
    title: "Cibersegurança ofensiva: pensando como atacante",
    category: "Palestras",
    date: getRelativeDate(0),
    time: "19:30 - 21:00",
    location: "Auditório Principal, Bloco A",
    hours: 2,
    spots: 150,
    enrolled: 142,
    speaker: "Eng. Felipe Andrade (Tempest)",
    description: "Como pentesters identificam vulnerabilidades em aplicações reais. Casos práticos com OWASP Top 10.",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    isEnrolled: true,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
  },
  {
    id: 1007,
    title: "Workshop: Construindo APIs com FastAPI",
    category: "Workshops",
    date: getRelativeDate(1),
    time: "14:00 - 17:00",
    location: "Laboratório 3, Bloco C",
    hours: 3,
    spots: 30,
    enrolled: 27,
    speaker: "Prof. Roberto Costa",
    description: "Construa do zero uma API REST completa com autenticação JWT, SQLAlchemy e documentação automática.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
    suggestedBy: "Lucas Bergmann",
  },

  // ============== ESTA SEMANA ==============
  {
    id: 1008,
    title: "STF e o futuro do direito digital",
    category: "Palestras",
    date: getRelativeDate(2),
    time: "19:00 - 21:00",
    location: "Auditório Menor, Bloco B",
    hours: 2,
    spots: 100,
    enrolled: 78,
    speaker: "Min. (apos.) Carlos Alberto Tavares",
    description: "Marco Civil, LGPD, IA Act e os desafios da regulação tecnológica vistos por um ex-ministro do STF.",
    image: "https://images.unsplash.com/photo-1589994965851-a8f479c573a9?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Direito", "Engenharia de Software", "Sistemas de Informação"],
  },
  {
    id: 1009,
    title: "Construções sustentáveis e ESG",
    category: "Palestras",
    date: getRelativeDate(3),
    time: "16:00 - 18:00",
    location: "Auditório de Engenharia, Bloco E",
    hours: 2,
    spots: 90,
    enrolled: 52,
    speaker: "Eng. Patrícia Bittencourt (Odebrecht)",
    description: "Certificações LEED, AQUA e Procel. Como o canteiro de obras está mudando para atender critérios ambientais.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia Civil", "Arquitetura e Urbanismo"],
  },
  {
    id: 1010,
    title: "Carreira em Big Tech: de júnior a sênior",
    category: "Palestras",
    date: getRelativeDate(4),
    time: "19:00 - 20:30",
    location: "Online (Google Meet)",
    hours: 2,
    spots: 200,
    enrolled: 134,
    speaker: "Eng. Mariana Tavares (ex-Google)",
    description: "Trajetória real de uma engenheira brasileira que atuou em três big techs. Dicas de processo seletivo e crescimento.",
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
  },
  {
    id: 1011,
    title: "Workshop: Petição inicial na prática",
    category: "Workshops",
    date: getRelativeDate(5),
    time: "13:00 - 17:00",
    location: "Sala 204, Bloco D",
    hours: 4,
    spots: 35,
    enrolled: 33,
    speaker: "Dra. Renata Vasconcelos (OAB-RJ)",
    description: "Da consulta inicial ao protocolo: estrutura, fundamentação e estratégia processual. Cada aluno escreve uma petição completa.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Direito"],
  },
  {
    id: 1012,
    title: "Workshop: React Native do zero ao deploy",
    category: "Workshops",
    date: getRelativeDate(6),
    time: "09:00 - 13:00",
    location: "Laboratório 4, Bloco C",
    hours: 4,
    spots: 25,
    enrolled: 25,
    speaker: "Profa. Ana Lima",
    description: "Crie um app mobile completo e publique na Play Store. Foco em performance, navegação e gerenciamento de estado.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80",
    isEnrolled: true,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
  },

  // ============== PRÓXIMAS SEMANAS ==============
  {
    id: 1013,
    title: "Saúde mental em ambientes acadêmicos",
    category: "Seminários",
    date: getRelativeDate(9),
    time: "18:30 - 20:30",
    location: "Auditório Principal, Bloco A",
    hours: 2,
    spots: 250,
    enrolled: 108,
    speaker: "Dra. Lúcia Mansur (CFP) / Psic. Bruno Bastos",
    description: "Síndrome do impostor, burnout acadêmico e ansiedade de desempenho. Painel aberto a perguntas anônimas.",
    image: "https://images.unsplash.com/photo-1499728603263-13726abce5fd?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Psicologia", "Geral"],
  },
  {
    id: 1014,
    title: "Workshop de SketchUp para arquitetos",
    category: "Workshops",
    date: getRelativeDate(11),
    time: "09:00 - 12:00",
    location: "Atelier 2, Bloco F",
    hours: 3,
    spots: 30,
    enrolled: 24,
    speaker: "Arq. Tatiana Resende",
    description: "Modelagem 3D do zero: planta, volumetria, materiais e renderização básica. Traga seu notebook com SketchUp instalado.",
    image: "https://images.unsplash.com/photo-1503387837-b154d5074bd2?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Arquitetura e Urbanismo"],
    suggestedBy: "Carolina Mendes",
  },
  {
    id: 1015,
    title: "Hackathon FlowUp 2026",
    category: "Eventos",
    date: getRelativeDate(12),
    time: "08:00 - 22:00",
    location: "Centro de Convenções, Bloco D",
    hours: 14,
    spots: 100,
    enrolled: 71,
    speaker: "Coordenação Acadêmica",
    description: "48 horas para construir um produto do zero. Equipes interdisciplinares, premiação em dinheiro e mentoria com profissionais do mercado.",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia de Software", "Sistemas de Informação", "Geral"],
  },
  {
    id: 1016,
    title: "Indústria 4.0: automação e sensores",
    category: "Palestras",
    date: getRelativeDate(14),
    time: "15:00 - 17:00",
    location: "Auditório de Engenharia, Bloco E",
    hours: 2,
    spots: 100,
    enrolled: 41,
    speaker: "Eng. Marcos Antunes (Siemens BR)",
    description: "Da CLP ao IIoT: como linhas de produção viraram coleta massiva de dados e o que isso muda na engenharia mecânica.",
    image: "https://images.unsplash.com/photo-1567789884554-0b844b597180?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia Mecânica", "Engenharia de Software"],
  },
  {
    id: 1017,
    title: "Jornalismo de dados na era da IA",
    category: "Palestras",
    date: getRelativeDate(16),
    time: "19:30 - 21:00",
    location: "Auditório Menor, Bloco B",
    hours: 2,
    spots: 80,
    enrolled: 35,
    speaker: "Jornalista Natália Viana (Pública)",
    description: "Reportagens investigativas que usam scraping, planilhas e visualização. Casos vencedores do Data Journalism Awards.",
    image: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Comunicação Social"],
  },
  {
    id: 1018,
    title: "Feira de Estágios e Carreiras 2026",
    category: "Eventos",
    date: getRelativeDate(17),
    time: "10:00 - 18:00",
    location: "Pavilhão Central",
    hours: 4,
    spots: 800,
    enrolled: 312,
    speaker: "Núcleo de Carreiras",
    description: "Mais de 40 empresas presentes. Vagas em todas as áreas: TI, saúde, engenharia, direito, comunicação, design e mais.",
    image: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Geral"],
  },
  {
    id: 1019,
    title: "Workshop: Docker e Kubernetes para devs",
    category: "Workshops",
    date: getRelativeDate(18),
    time: "13:30 - 17:30",
    location: "Laboratório 3, Bloco C",
    hours: 4,
    spots: 25,
    enrolled: 19,
    speaker: "Eng. Bruno Carmo (Stone)",
    description: "Da imagem ao cluster: empacote sua aplicação, suba no Kubernetes e configure CI/CD com GitHub Actions.",
    image: "https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
    suggestedBy: "Carolina Mendes",
  },
  {
    id: 1020,
    title: "Atualizações em Endodontia",
    category: "Seminários",
    date: getRelativeDate(20),
    time: "08:30 - 12:30",
    location: "Anfiteatro de Odontologia",
    hours: 4,
    spots: 60,
    enrolled: 28,
    speaker: "Dra. Patrícia Madureira (ABO-RJ)",
    description: "Novos protocolos de obturação, microscopia operatória e instrumentação rotatória. Inclui hands-on em modelo.",
    image: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Odontologia"],
  },
  {
    id: 1021,
    title: "Empreendedorismo Universitário: do TCC à startup",
    category: "Palestras",
    date: getRelativeDate(22),
    time: "19:30 - 21:00",
    location: "Auditório Principal, Bloco A",
    hours: 2,
    spots: 200,
    enrolled: 47,
    speaker: "Empreendedor Tiago Lourenço",
    description: "Cases reais de TCCs que viraram empresas. Como buscar investimento anjo, escolher sócios e validar ideia ainda na faculdade.",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Administração", "Engenharia de Software", "Sistemas de Informação", "Geral"],
  },
  {
    id: 1022,
    title: "Visita técnica: Museu do Amanhã (arquitetura)",
    category: "Eventos",
    date: getRelativeDate(24),
    time: "13:00 - 18:00",
    location: "Praça Mauá, Rio de Janeiro (encontro no portão)",
    hours: 5,
    spots: 40,
    enrolled: 32,
    speaker: "Profa. Beatriz Calmon",
    description: "Visita guiada com olhar técnico sobre o projeto de Calatrava: forma, estrutura, sustentabilidade e impacto urbano.",
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Arquitetura e Urbanismo"],
  },
  {
    id: 1023,
    title: "Workshop: Metodologias ativas em sala de aula",
    category: "Workshops",
    date: getRelativeDate(26),
    time: "08:00 - 12:00",
    location: "Sala 312, Bloco G",
    hours: 4,
    spots: 30,
    enrolled: 11,
    speaker: "Profa. Marlene Carvalho",
    description: "Sala de aula invertida, PBL, gamificação e avaliação por rubricas. Construa um plano de aula seguindo cada metodologia.",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Pedagogia"],
  },
  {
    id: 1024,
    title: "Workshop: Introdução a LLMs e RAG na prática",
    category: "Workshops",
    date: getRelativeDate(28),
    time: "09:00 - 12:00",
    location: "Laboratório 4, Bloco C",
    hours: 3,
    spots: 35,
    enrolled: 9,
    speaker: "Pesq. Diego Almeida (PUC-Rio)",
    description: "Construa um chatbot que responde sobre seus próprios documentos. OpenAI API + embeddings + vetor store.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80",
    isEnrolled: false,
    courses: ["Engenharia de Software", "Sistemas de Informação"],
    suggestedBy: "Mariana Silva",
  },
];

export const INITIAL_SUGGESTIONS = [
  {
    id: 2001,
    student: "Mariana Silva",
    avatar: "https://i.pravatar.cc/150?img=5",
    course: "Engenharia de Software",
    title: "Introdução a LLMs e RAG na prática",
    description: "Seria muito legal um workshop ensinando a montar um chatbot com a OpenAI API que responde sobre PDFs nossos.",
    date: getRelativeDate(-25),
    status: 'aprovada',
  },
  {
    id: 2002,
    student: "Mariana Silva",
    avatar: "https://i.pravatar.cc/150?img=5",
    course: "Engenharia de Software",
    title: "Mesa redonda sobre saúde mental no tech",
    description: "Estresse, burnout, síndrome do impostor — tudo isso ataca cedo na carreira e quase ninguém fala sobre.",
    date: getRelativeDate(-2),
    status: 'pendente',
  },
  {
    id: 2003,
    student: "Lucas Bergmann",
    avatar: "https://i.pravatar.cc/150?img=12",
    course: "Sistemas de Informação",
    title: "Workshop: Construindo APIs com FastAPI",
    description: "Tem muito tutorial de Flask por aí, mas FastAPI é o que o mercado tá pedindo. Faltaria um workshop hands-on.",
    date: getRelativeDate(-14),
    status: 'aprovada',
  },
  {
    id: 2004,
    student: "Carolina Mendes",
    avatar: "https://i.pravatar.cc/150?img=23",
    course: "Arquitetura e Urbanismo",
    title: "Workshop de SketchUp para arquitetos",
    description: "A galera do 3º período tá apanhando muito de SketchUp. Bora juntar todo mundo num workshop só?",
    date: getRelativeDate(-30),
    status: 'aprovada',
  },
  {
    id: 2005,
    student: "João Pedro Oliveira",
    avatar: "https://i.pravatar.cc/150?img=33",
    course: "Direito",
    title: "Simulado da OAB com correção comentada",
    description: "Trazer um cursinho parceiro para aplicar um simulado e fazer correção comentada das questões mais cobradas.",
    date: getRelativeDate(-5),
    status: 'pendente',
  },
  {
    id: 2006,
    student: "Ana Beatriz Ferreira",
    avatar: "https://i.pravatar.cc/150?img=47",
    course: "Medicina",
    title: "Workshop de sutura para iniciantes",
    description: "A gente só vê sutura no internato. Seria muito útil ter um workshop básico antes, em modelo, no 3º/4º período.",
    date: getRelativeDate(-1),
    status: 'pendente',
  },
  {
    id: 2007,
    student: "Isabela Rocha",
    avatar: "https://i.pravatar.cc/150?img=49",
    course: "Psicologia",
    title: "Roda de conversa: escuta clínica na adolescência",
    description: "Tema pouco discutido em sala. Convidar psicólogos da rede pública para uma conversa aberta.",
    date: getRelativeDate(-6),
    status: 'pendente',
  },
  {
    id: 2008,
    student: "Rafael Souza",
    avatar: "https://i.pravatar.cc/150?img=15",
    course: "Engenharia Civil",
    title: "Visita técnica a uma obra de grande porte",
    description: "Tem várias obras grandes no Porto Maravilha. Seria incrível visitar uma com engenheiro responsável explicando tudo.",
    date: getRelativeDate(-4),
    status: 'pendente',
  },
  {
    id: 2009,
    student: "Larissa Carvalho",
    avatar: "https://i.pravatar.cc/150?img=26",
    course: "Comunicação Social",
    title: "Curso de fotojornalismo com câmera de celular",
    description: "Não precisa de DSLR para fazer reportagem visual de qualidade. Workshop prático de enquadramento, luz e edição mobile.",
    date: getRelativeDate(-8),
    status: 'pendente',
  },
];

// ======================================================================
// HUB FlowUp — cursos assincronos patrocinados por parceiros institucionais
// ======================================================================

export const HUB_CATEGORIES = [
  "Todos",
  "Tecnologia",
  "Saúde",
  "Direito",
  "Negócios",
  "Sustentabilidade",
  "Engenharia",
  "Design",
  "Soft Skills",
  "Idiomas",
  "Humanidades",
];

export const HUB_LEVELS = ["Todos", "Iniciante", "Intermediário", "Avançado"];

// Parceiros institucionais. `accent` define a cor do avatar/badge no card.
export const HUB_PARTNERS = [
  { id: "alura",    name: "Alura",                       initials: "AL", accent: "indigo",  description: "Maior escola de tecnologia online do Brasil." },
  { id: "rocket",   name: "Rocketseat",                  initials: "RS", accent: "fuchsia", description: "Comunidade e treinamentos para devs de produto." },
  { id: "dio",      name: "DIO",                         initials: "DI", accent: "amber",   description: "Bootcamps gratuitos em parceria com grandes empresas." },
  { id: "fgv",      name: "FGV Online",                  initials: "FG", accent: "sky",     description: "Cursos abertos da Fundação Getúlio Vargas." },
  { id: "usp",      name: "USP / edX",                   initials: "US", accent: "rose",    description: "Cursos abertos da Universidade de São Paulo via edX." },
  { id: "einstein", name: "Albert Einstein Educação",    initials: "AE", accent: "emerald", description: "Educação médica continuada do Hospital Israelita Albert Einstein." },
  { id: "oab",      name: "OAB Cursos",                  initials: "OB", accent: "red",     description: "Atualização profissional da Ordem dos Advogados do Brasil." },
  { id: "sebrae",   name: "Sebrae",                      initials: "SB", accent: "teal",    description: "Cursos para empreendedores em qualquer estágio." },
  { id: "senai",    name: "Senai EAD",                   initials: "SE", accent: "orange",  description: "Capacitação técnica e industrial a distância." },
  { id: "casa",     name: "Casa do Saber",               initials: "CS", accent: "violet",  description: "Aulas de filosofia, história e ciências humanas." },
];

// Cada curso aponta para um partner.id de HUB_PARTNERS.
// `image` usa Unsplash com URLs já validadas. `link` é externo (placeholder #).
export const HUB_COURSES = [
  {
    id: 3001,
    title: "Python para Data Science",
    partnerId: "alura",
    category: "Tecnologia",
    level: "Intermediário",
    hours: 24,
    format: "Online assíncrono",
    price: "Grátis para alunos FlowUp",
    description: "Pandas, NumPy, Matplotlib e o ciclo completo de análise de dados. Projetos com datasets reais do governo brasileiro.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    enrollments: 247,
    isFeatured: true,
    isRecommended: true,
    link: "#",
  },
  {
    id: 3002,
    title: "React do zero ao deploy",
    partnerId: "rocket",
    category: "Tecnologia",
    level: "Iniciante",
    hours: 20,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Hooks modernos, Context, roteamento e deploy na Vercel. Constrói um portfólio completo no final.",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80",
    enrollments: 412,
    isRecommended: true,
    link: "#",
  },
  {
    id: 3003,
    title: "Bootcamp Cloud Computing AWS",
    partnerId: "dio",
    category: "Tecnologia",
    level: "Avançado",
    hours: 60,
    format: "Bootcamp com mentoria",
    price: "Patrocinado pela AWS",
    description: "EC2, S3, Lambda, IAM e arquiteturas serverless. Certificação Cloud Practitioner ao final.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    enrollments: 89,
    isFeatured: true,
    link: "#",
  },
  {
    id: 3004,
    title: "Gestão de Projetos Ágeis",
    partnerId: "fgv",
    category: "Negócios",
    level: "Iniciante",
    hours: 16,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Scrum, Kanban e os princípios do manifesto ágil aplicados em projetos universitários e corporativos.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80",
    enrollments: 156,
    link: "#",
  },
  {
    id: 3005,
    title: "Mudanças Climáticas: Ciência e Impacto",
    partnerId: "usp",
    category: "Sustentabilidade",
    level: "Iniciante",
    hours: 12,
    format: "Online assíncrono",
    price: "Grátis (auditoria)",
    description: "Como cientistas medem o aquecimento global, projeções de cenário e implicações para políticas públicas.",
    image: "https://images.unsplash.com/photo-1500964757637-c85e8a162699?auto=format&fit=crop&w=800&q=80",
    enrollments: 73,
    isRecommended: true,
    link: "#",
  },
  {
    id: 3006,
    title: "Suporte Básico de Vida (BLS)",
    partnerId: "einstein",
    category: "Saúde",
    level: "Iniciante",
    hours: 8,
    format: "Online + prova presencial",
    price: "Grátis para alunos de Medicina/Odonto",
    description: "Protocolos da AHA para parada cardiorrespiratória, desobstrução de vias aéreas e uso do DEA.",
    image: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&w=800&q=80",
    enrollments: 198,
    isFeatured: true,
    link: "#",
  },
  {
    id: 3007,
    title: "Atendimento ao paciente idoso",
    partnerId: "einstein",
    category: "Saúde",
    level: "Intermediário",
    hours: 20,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Polifarmácia, fragilidade, comunicação com o cuidador e particularidades clínicas da terceira idade.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    enrollments: 64,
    link: "#",
  },
  {
    id: 3008,
    title: "LGPD na prática para advogados",
    partnerId: "oab",
    category: "Direito",
    level: "Intermediário",
    hours: 18,
    format: "Online assíncrono",
    price: "Grátis para estudantes de Direito",
    description: "Casos reais de adequação à LGPD, contratos com cláusulas obrigatórias e atuação do encarregado (DPO).",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80",
    enrollments: 142,
    isRecommended: true,
    link: "#",
  },
  {
    id: 3009,
    title: "Empreendedorismo Digital",
    partnerId: "sebrae",
    category: "Negócios",
    level: "Iniciante",
    hours: 10,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Validação de ideias, modelos de negócio digital e ferramentas gratuitas para começar com zero capital.",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80",
    enrollments: 305,
    link: "#",
  },
  {
    id: 3010,
    title: "Plano de Negócios em 30 dias",
    partnerId: "sebrae",
    category: "Negócios",
    level: "Iniciante",
    hours: 30,
    format: "Online com mentoria",
    price: "Grátis",
    description: "Um plano de negócios completo ao final do curso, com canvas, projeção financeira e pitch pronto.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
    enrollments: 117,
    link: "#",
  },
  {
    id: 3011,
    title: "Indústria 4.0: Fundamentos",
    partnerId: "senai",
    category: "Engenharia",
    level: "Intermediário",
    hours: 40,
    format: "Online assíncrono",
    price: "Grátis",
    description: "IoT industrial, manufatura aditiva, big data fabril e simulação. Direcionado para engenharia mecânica e produção.",
    image: "https://images.unsplash.com/photo-1567789884554-0b844b597180?auto=format&fit=crop&w=800&q=80",
    enrollments: 58,
    link: "#",
  },
  {
    id: 3012,
    title: "UX Design: Fundamentos",
    partnerId: "alura",
    category: "Design",
    level: "Iniciante",
    hours: 22,
    format: "Online assíncrono",
    price: "Grátis para alunos FlowUp",
    description: "Pesquisa com usuários, arquitetura de informação, wireframes no Figma e princípios de usabilidade de Nielsen.",
    image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&w=800&q=80",
    enrollments: 184,
    link: "#",
  },
  {
    id: 3013,
    title: "Inteligência Emocional no Trabalho",
    partnerId: "fgv",
    category: "Soft Skills",
    level: "Iniciante",
    hours: 15,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Autoconsciência, empatia, gestão de conflitos e como dar feedback difícil. Aplicável a qualquer carreira.",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80",
    enrollments: 391,
    isFeatured: true,
    isRecommended: true,
    link: "#",
  },
  {
    id: 3014,
    title: "Inglês para entrevistas técnicas",
    partnerId: "alura",
    category: "Idiomas",
    level: "Intermediário",
    hours: 20,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Vocabulário e estrutura de respostas em inglês para entrevistas em big techs. Inclui simulados gravados.",
    image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80",
    enrollments: 226,
    link: "#",
  },
  {
    id: 3015,
    title: "Direito Empresarial Aplicado",
    partnerId: "fgv",
    category: "Direito",
    level: "Intermediário",
    hours: 20,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Contratos, M&A, governança corporativa e tributação para advogados que querem migrar para o setor empresarial.",
    image: "https://images.unsplash.com/photo-1589994965851-a8f479c573a9?auto=format&fit=crop&w=800&q=80",
    enrollments: 84,
    link: "#",
  },
  {
    id: 3016,
    title: "Filosofia para o Século XXI",
    partnerId: "casa",
    category: "Humanidades",
    level: "Iniciante",
    hours: 12,
    format: "Online assíncrono",
    price: "Grátis",
    description: "Como filósofos contemporâneos pensam IA, redes sociais, ecologia e o sentido do trabalho. Aulas curtas e diárias.",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80",
    enrollments: 132,
    link: "#",
  },
  {
    id: 3017,
    title: "Genética e Biotecnologia Básica",
    partnerId: "usp",
    category: "Saúde",
    level: "Avançado",
    hours: 28,
    format: "Online assíncrono",
    price: "Grátis (auditoria)",
    description: "Do DNA ao CRISPR. Curso introdutório para estudantes que querem migrar para pesquisa ou medicina de precisão.",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80",
    enrollments: 41,
    link: "#",
  },
  {
    id: 3018,
    title: "Marketing Digital para Empreendedores",
    partnerId: "sebrae",
    category: "Negócios",
    level: "Iniciante",
    hours: 18,
    format: "Online assíncrono",
    price: "Grátis",
    description: "SEO básico, Instagram orgânico, anúncios pagos e analytics. Plano de marketing pronto ao final.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    enrollments: 273,
    link: "#",
  },
];

// Trilhas: sequências curadas de cursos com tema único.
// `courseIds` referencia HUB_COURSES.id na ordem sugerida.
export const HUB_TRAILS = [
  {
    id: 4001,
    title: "Dev Full-Stack do Zero",
    subtitle: "Da primeira linha de código ao primeiro deploy em produção",
    accent: "indigo",
    icon: "Code2",
    totalHours: 90,
    courseIds: [3002, 3001, 3014, 3003],
    description: "Pra quem quer migrar pra desenvolvimento sem nenhuma base. Estrutura progressiva: front-end → dados → inglês técnico → cloud.",
  },
  {
    id: 4002,
    title: "Saúde Mental no Ambiente Acadêmico",
    subtitle: "Ferramentas pra atravessar a faculdade inteiro",
    accent: "emerald",
    icon: "Heart",
    totalHours: 47,
    courseIds: [3013, 3016, 3005],
    description: "Curadoria transversal: regulação emocional, perspectiva filosófica e consciência ambiental. Aberto a qualquer curso.",
  },
  {
    id: 4003,
    title: "Empreendedor Acadêmico",
    subtitle: "Saia da faculdade com uma empresa pronta",
    accent: "amber",
    icon: "Rocket",
    totalHours: 78,
    courseIds: [3009, 3010, 3018, 3013],
    description: "Trajetória completa: ideia → modelo de negócio → plano formal → marketing → soft skills pra liderar time.",
  },
  {
    id: 4004,
    title: "Profissional do Futuro",
    subtitle: "Pra quem quer chegar pronto no mercado em 2030",
    accent: "fuchsia",
    icon: "Sparkles",
    totalHours: 67,
    courseIds: [3001, 3012, 3013, 3014],
    description: "Habilidades cruzadas que o mercado paga caro: dados, design, comunicação humana e inglês técnico.",
  },
];
